name: Build and Test C Program

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build C program
      run: |
        cd $GITHUB_WORKSPACE/test  # Change to the 'test' directory
        gcc -o my_program hello.c

    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE/test  # Change to the 'test' directory
        gcc -o test_program main.c
        ./test_program
